name: clockify
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  google_fonts: ^6.2.1
  table_calendar: ^3.2.0
  flutter:
    sdk: flutter
  shadcn_flutter:
    path: packs/shadcn_flutter
  sqflite: ^2.4.2
  path: ^1.9.1
  shared_preferences: ^2.5.2
  intl: ^0.20.2
  http: ^1.3.0
  html: ^0.15.5
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  fonts:
    - family: "GeistSans"
      fonts:
        - asset: packs/shadcn_flutter/lib/fonts/Geist-Black.otf
          weight: 800
        - asset: packs/shadcn_flutter/lib/fonts/Geist-Bold.otf
          weight: 700
        - asset: packs/shadcn_flutter/lib/fonts/Geist-Light.otf
          weight: 300
        - asset: packs/shadcn_flutter/lib/fonts/Geist-Medium.otf
          weight: 500
        - asset: packs/shadcn_flutter/lib/fonts/Geist-SemiBold.otf
          weight: 600
        - asset: packs/shadcn_flutter/lib/fonts/Geist-Thin.otf
          weight: 100
        - asset: packs/shadcn_flutter/lib/fonts/Geist-UltraBlack.otf
          weight: 900
        - asset: packs/shadcn_flutter/lib/fonts/Geist-UltraLight.otf
          weight: 200
        - asset: packs/shadcn_flutter/lib/fonts/Geist-Regular.otf
          weight: 400
    - family: "GeistMono"
      fonts:
        - asset: packs/shadcn_flutter/lib/fonts/GeistMono-Black.otf
          weight: 800
        - asset: packs/shadcn_flutter/lib/fonts/GeistMono-Bold.otf
          weight: 700
        - asset: packs/shadcn_flutter/lib/fonts/GeistMono-Light.otf
          weight: 300
        - asset: packs/shadcn_flutter/lib/fonts/GeistMono-Medium.otf
          weight: 500
        - asset: packs/shadcn_flutter/lib/fonts/GeistMono-Regular.otf
          weight: 400
        - asset: packs/shadcn_flutter/lib/fonts/GeistMono-SemiBold.otf
          weight: 600
        - asset: packs/shadcn_flutter/lib/fonts/GeistMono-Thin.otf
          weight: 100
        - asset: packs/shadcn_flutter/lib/fonts/GeistMono-UltraBlack.otf
          weight: 900
        - asset: packs/shadcn_flutter/lib/fonts/GeistMono-UltraLight.otf
          weight: 200
    
    - family: RadixIcons
      fonts:
        - asset: packs/shadcn_flutter/lib/icons/RadixIcons.otf
    - family: BootstrapIcons
      fonts:
        - asset: packs/shadcn_flutter/lib/icons/BootstrapIcons.otf
    

  assets:
    - lib/assets/on-time.png
    - lib/assets/calendar.png
  uses-material-design: true
